version: '3'
services:
  web:
    image: anytask
    environment:
      - DJANGO_SETTINGS_MODULE=anytask.settings_docker
    restart: always
    ports:
      - 80:80
    volumes:
      - ./data:/app/data
